name: Build with setup-gradle

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Print Gradle location on PATH
      run: which 'gradle'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@release/use-wrapper-for-cleanup
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-use-agree: "yes"
        gradle-version: "8.13-milestone-3"

    - name: Print provisioned version
      run: gradle --version

    - name: Execute Gradle build
      run: ./gradlew build

    - name: Execute Gradle build with 8.12 (not wrapper)
      run: /usr/bin/gradle build
