name: Build with setup-gradle

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@main
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-use-agree: "yes"
      env:
        GRADLE_BUILD_ACTION_CACHE_KEY_PREFIX: "A-very-long-prefix-that-should-make-the-key-too-long-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

    - name: Execute Gradle build
      run: ./gradlew build
