name: Build with setup-gradle

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@release/use-wrapper-for-cleanup
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-use-agree: "yes"
        gradle-version: "nightly"

    - name: Print env & toolchains.xml
      run: |
        env | grep '^JAVA'
        cat $HOME/.m2/toolchains.xml

    - name: Execute Gradle build
      run: ./gradlew build

    - name: Print Gradle toolchains
      run: ./gradlew --info javaToolchains
