name: Build with setup-gradle

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gradle/actions/setup-gradle@prerelease/v4
      with:
        arguments: assemble
    # - run: ./gradlew assemble
