name: Build with setup-gradle

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@release/toolchains-xml

    - name: Print toolchains.xml
      run: cat /home/runner/.m2/toolchains.xml

    - name: Execute Gradle build
      run: ./gradlew --info javaToolchains
