name: Test deprecated behaviours

on:
  push:
  workflow_dispatch:

jobs:
  gradle-build-action-v2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - uses: gradle/gradle-build-action@v2

    - name: Execute Gradle build
      run: ./gradlew build

  gradle-build-action-v3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - uses: gradle/gradle-build-action@v3

    - name: Execute Gradle build
      run: ./gradlew build

  gradle-build-action-v3-with-arguments:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - uses: gradle/gradle-build-action@v3
      with:
        arguments: build

  setup-gradle-v3-with-arguments:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - uses: gradle/actions/setup-gradle@v3
      with:
        arguments: build

  setup-gradle-v4-with-arguments:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - uses: gradle/actions/setup-gradle@v4
      with:
        arguments: build
