name: Test deprecated behaviours

on:
  push:
  workflow_dispatch:

jobs:
  gradle-build-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - uses: gradle/gradle-build-action@v3

    - name: Execute Gradle build
      run: ./gradlew build

  gradle-build-action-with-arguments:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - uses: gradle/gradle-build-action@v3
      with:
        arguments: build

  setup-gradle-with-arguments:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - uses: gradle/actions/setup-gradle@v3
      with:
        arguments: build
