name: Test different configs for slow post-action 

on:
  push:
  workflow_dispatch:

jobs:
  build-v2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gradle/gradle-build-action@v2
    - run: ./gradlew assemble

  build-v3-beta:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gradle/gradle-build-action@v3-beta
    - run: ./gradlew assemble

  build-cache-read-only:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gradle/gradle-build-action@v3-beta
      with:
        cache-read-only: true
    - run: ./gradlew assemble
